### ISSUE TITLE
Collect information about what to do for each TYPO3 release (related to documentation)

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/T3DocTeam#102]
## for a new major release:

What's new slides:

*  make sure to link to documentation and use links with correct version (not master), depends on #101 

core

* Change version in Settings.cfg of sysexts with Documentation in core (`version = ...`)
* Change version in URL of intersphinx linking in Settings.cfg of branch that just got created from master

main documentation

* Branch out (create version branch from master)  
   * update URLs in Settings.cfg for intesphinx linking
   * update external URLS: https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-Installation/pull/113
   * change version = in Settings.cfg
   * change composer.json
* update documentation

## todos

* [ ]  collect information about the changes
* [ ] a lot of this can be scripted: create scripts / refer to existing scripts
* [ ] add information to central release documentation (or add link and document somewhere else)

## Related

* #101 
* #81

**Comment by sypets** [comment]
@DanielSiepmann You assigned yourself - are you still working on this? Should we close?

**Comment by DanielSiepmann** [comment]
I'm no longer working on this. And I can't decide if we should close. Would guess that's up to the active folks.

**Comment by linawolf** [comment]
yes we should...
