### ISSUE TITLE
Documentation updates related to Changelog 10.0

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/T3DocTeam#114]
Breaking
* [ ] [Breaking: #21638 - AbstractUserAuthentication::lockIP property removed](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-21638-LockIPPropertyRemoved.html)
* [ ] [Breaking: #81950 - Remove leftover workspaces unpublishing functionality](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-81950-RemoveLeftoverWorkspacesUnpublishingFunctionality.html)
* [ ] [Breaking: #86862 - Default Layout of ext:fluid_styled_content does not use spaceless viewHelper anymore](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-86862-DefaultLayoutOfExtfluid_styled_contentDoesNotUseSpacelessViewHelperAnymore.html)
* [ ] [Breaking: #87009 - Use multiple translation files by default in EXT:form](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-87009-UseMultipleTranslationFilesByDefaultInEXTform.html)
* [ ] [Breaking: #87193 - Deprecated functionality removed](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-87193-DeprecatedFunctionalityRemoved.html)
* [ ] [Breaking: #87305 - Use constructor injection in DataMapper](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-87305-UseConstructorInjectionInDataMapper.html)
* [ ] [Breaking: #87511 - Remove $namespacesViewObjectNamePattern property](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-87511-RemoveNamespacesViewObjectNamePatternProperty.html)
* [ ] [Breaking: #87511 - Remove $viewFormatToObjectNameMap property](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-87511-RemoveViewFormatToObjectNameMapProperty.html)
* [ ] [Breaking: #87558 - Consolidate extbase caches](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-87558-ConsolidateExtbaseCaches.html)
* [ ] [Breaking: #87567 - Global variable $TBE_TEMPLATE removed](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-87567-GlobalVariableTBE_TEMPLATERemoved.html)
* [ ] [Breaking: #87583 - Remove obsolete APC Cache Backend implementation](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-87583-RemoveObsoleteAPCCacheBackendImplementation.html)
* [ ] [Breaking: #87594 - Harden extbase](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-87594-HardenExtbase.html)
* [ ] [Breaking: #87623 - Replace config.persistence.classes typoscript configuration](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-87623-ReplaceConfigpersistenceclassesTyposcriptConfiguration.html)
* [ ] [Breaking: #87627 - Remove Property extensionName of AbstractController](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-87627-RemovePropertyExtensionNameOfAbstractController.html)
* [ ] [Breaking: #87936 - TCA for sys_history removed](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-87936-TCAForSysHistoryRemoved.html)
* [ ] [Breaking: #87937 - TCA option “selicon_field_path” removed](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-87937-TCAOption_selicon_field_path_removed.html)
* [ ] [Breaking: #87957 - Validators are not registered automatically in Extbase anymore](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-87957-DoNotMagicallyRegisterValidators.html)
* [ ] [Breaking: #87989 - TCA option setToDefaultOnCopy removed](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-87989-TCAOptionSetToDefaultOnCopyRemoved.html)
* [ ] [Breaking: #88129 - Renamed felogin flexform fields](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-88129-RenameFeloginFlexformFields.html)
* [ ] [Breaking: #88143 - Version-related database field “t3ver_id” removed](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-88143-Version-relatedDatabaseFieldT3ver_idRemoved.html)
* [ ] [Breaking: #88182 - jsfunc.inline.js has been dropped](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-88182-JsfuncInlineJsHasBeenDropped.html)
* [ ] [Breaking: #88366 - Removed prefix of cache tables](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-88366-RemovedCf_PrefixOfCacheTables.html)
* [ ] [Breaking: #88376 - Removed obsolete “pageNotFound_handling” settings](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-88376-RemovedObsoletePageNotFound_handlingSettings.html)
* [ ] [Breaking: #88411 - TBE_EDITOR.typo3form removed](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-88411-TBE_EDITORtypo3formRemoved.html)
* [ ] [Breaking: #88427 - jsfunc.evalfield.js has been removed](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-88427-JsfuncevalfieldjsHasBeenRemoved.html)
* [ ] [Breaking: #88458 - Removed Frontend Track User “ftu” functionality](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-88458-RemovedFrontendTrackUserFtuFunctionality.html)
* [ ] [Breaking: #88496 - Method getSwitchableControllerActions has been removed](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-88496-MethodGetSwitchableControllerActionsHasBeenRemoved.html)
* [ ] [Breaking: #88498 - Global data for TimeTracker statistics removed](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-88498-GlobalDataForTimeTrackerStatisticsRemoved.html)
* [ ] [Breaking: #88500 - RTE image handling functionality dropped](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-88500-RTEImageHandlingFunctionalityDropped.html)
* [ ] [Breaking: #88525 - Remove “createDirs” directive of extension installation / em_conf.php](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-88525-RemoveCreateDirsDirectiveOfExtensionInstallationEm_confphp.html)
* [ ] [Breaking: #88527 - Overriding custom values in User Authentication derivatives](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-88527-OverridingCustomValuesInUserAuthenticationDerivatives.html)
* [ ] [Breaking: #88540 - Changed Request Workflow for Frontend Requests](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-88540-ChangedRequestWorkflowForFrontendRequests.html)
* [ ] [Breaking: #88564 - PageTSconfig setting “TSFE.constants” removed](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-88564-PageTSconfigSettingTSFEconstantsRemoved.html)
* [ ] [Breaking: #88574 - 4th parameter of PageRepository->enableFields removed](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-88574-4thParameterOfPageRepository-enableFieldsRemoved.html)
* [ ] [Breaking: #88583 - Database field sys_language.static_lang_isocode removed](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-88583-DatabaseFieldSys_languagestatic_lang_isocodeRemoved.html)
* [ ] [Breaking: #88638 - Streamlined SoftRefParser reference lookup](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-88638-StreamlinedSoftRefParserReferenceLookup.html)
* [ ] [Breaking: #88640 - Database field “sys_template.nextLevel” and TypoScript sublevel - inheritance removed](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-88640-DatabaseFieldSys_templatenextLevelAndTypoScriptSublevel-InheritanceRemoved.html)
* [ ] [Breaking: #88643 - Removed swiftmailer/swiftmailer dependency](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-88643-RemovedSwiftmailerswiftmailerDependency.html) ( **missing:**, see [old documentation based on SwiftMailer](https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/Mail/Index.html))
* [ ] [Breaking: #88646 - Removed inheritance of AbstractService from AbstractAuthenticationService](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-88646-RemovedInheritanceOfAbstractServiceFromAbstractAuthenticationService.html)
* [ ] [Breaking: #88657 - Popup configuration in FormEngine dropped](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-88657-PopupConfigurationInFormEngineDropped.html)
* [ ] [Breaking: #88660 - $GLOBALS[T3_VAR] removed](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-88660-GLOBALST3_VARRemoved.html)
* [ ] [Breaking: #88667 - Removed additionalJavaScriptSubmit from FormEngine](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-88667-RemovedAdditionalJavaScriptSubmitFromFormEngine.html)
* [ ] [Breaking: #88669 - FormEngine FormDataProvider “parentPageTca” removed](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-88669-FormEngineFormDataProviderParentPageTcaRemoved.html)
* [ ] [Breaking: #88681 - Import of PHP files in Import/Export files removed](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-88681-ImportOfPHPFilesInImportExportFilesRemoved.html)
* [ ] [Breaking: #88687 - Configure extbase request handlers via PHP](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-88687-ConfigureExtbaseRequestHandlersViaPHP.html)
* [ ] [Breaking: #88706 - Streamline felogin locallang keys](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-88706-StreamlineFeloginLocallangKeys.html)
* [ ] [Breaking: #88724 - Remove superfluous methods of localizationRedirect](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-88724-RemoveSuperfluousMethodsOfLocalizationRedirect.html)
* [ ] [Breaking: #88741 - cHash calculation in indexed search removed](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-88741-CHashCalculationInIndexedSearchRemoved.html)
* [ ] [Breaking: #88744 - Database fields related to CSS Styled Content removed](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-88744-DatabaseFieldsRelatedToCSSStyledContentRemoved.html)
* [ ] [Breaking: #88755 - Remove POST option from typolink.addQueryString.method](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-88755-RemovePOSTOptionFromTypolinkaddQueryStringmethod.html)
* [ ] [Breaking: #88758 - Selective Concatenation of CSS files in ResourceCompressor removed](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-88758-SelectiveConcatenationOfCSSFilesInResourceCompressorRemoved.html)
* [ ] [Breaking: #88772 - JavaScript script tags omit type=text/javascript in HTML5](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-88772-JavaScriptScriptTagsOmitTypetextjavascriptInHTML5.html)
* [ ] [Breaking: #88779 - RecordList: Remove unused code](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-88779-RecordListRemoveUnusedCode.html)
* [ ] [Breaking: #88799 - Introduced PSR-3 compatible Logging API](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-88799-IntroducedPSR-3CompatibleLoggingAPI.html)

Features
* [ ] [Feature: #21638 - Introduced IP locking for IPv6](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Feature-21638-IntroducedIpLockingForIpv6.html)
* [ ] [Feature: #56213 - Allow sorting file list by file meta data “title”](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Feature-56213-AllowSortingFilelistByFileMetadataTitle.html)
* [ ] [Feature: #78432 - Add log message for “Switch User action”](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Feature-78432-AddLogMessageForSwitchUserAction.html)
* [ ] [Feature: #80420 - Allow multiple recipients in email finisher](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Feature-80420-AllowMultipleRecipientsInEmailFinisher.html)
* [ ] [Feature: #83734 - Add support for current page in config.cache](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Feature-83734-AddSupportForCurrentPageInConfigcache.html)
* [ ] [Feature: #84112 - Symfony dependency injection for core and extbase](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Feature-84112-SymfonyDependencyInjectionForCoreAndExtbase.html) - **in progress**, see issue https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/595
* [ ] [Feature: #84757 - Double click in structure tree changes label](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Feature-84757-DoubleClickInStructureTreeChangesLabel.html)
* [ ] [Feature: #85569 - Show scheduler information in the system information toolbar](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Feature-85569-ShowSchedulerInformationsInTheSystemInformationToolbar.html)
* [ ] [Feature: #85607 - New ThumbnailViewHelper to render thumbnails deferred](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Feature-85607-NewThumbnailViewHelperToRenderThumbnailsDeferred.html)
* [ ] [Feature: #86629 - Implement LinkHandler for telephone numbers](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Feature-86629-ImplementLinkHandlerForTelephoneNumbers.html)
* [ ] [Feature: #86964 - Allow getting class property default value](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Feature-86964-AllowGettingClassPropertyDefaultValue.html)
* [ ] [Feature: #87200 - Send plaintext and HTML mails in EmailFinisher](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Feature-87200-SendPlaintextAndHTMLMailsInEmailFinisher.html)
* [ ] [Feature: #87433 - Add changefreq and priority for XML sitemap](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Feature-87433-AddChangefreqAndPriority.html)
* [ ] [Feature: #87457 - Use symfony/property-info to gather doc block information](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Feature-87457-UseSymfonyproperty-infoToGatherDocBlockInformation.html)
* [ ] [Feature: #87665 - Introduce BitSet class](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Feature-87665-IntroduceBitSetClass.html)
* [ ] [Feature: #87726 - Extend FrontendLoginController Hook to validate password](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Feature-87726-ExtendFrontendLoginControllerHookToValidatePassword.html)
* [ ] [Feature: #88643 - New Mail API based on symfony/mailer and symfony/mime](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Feature-88643-NewMailAPIBasedOnSymfonymailerAndSymfonymime.html)
* [ ] [Feature: #88648 - Set Twitter Card Type in page properties](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Feature-88648-DefineTwitterCardTypeInPageProperties.html)
* [ ] [Feature: #88770 - PSR-14 based EventDispatcher](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Feature-88770-PSR-14BasedEventDispatcher.html) **PR in progress :** https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/616
* [ ] [Feature: #88791 - Introduce PreviewAspect in Context](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Feature-88791-IntroducePreviewAspectInContext.html)
* [ ] [Feature: #88792 - Add TypoScriptAspect to handle TypoScript Rendering Context settings](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Feature-88792-AddTypoScriptAspectToHandleTypoScriptRenderingContextSettings.html)
* [ ] [Feature: #88799 - Introduced PSR-3 compatible Logging API](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Feature-88799-IntroducedPSR-3CompatibleLoggingAPI.html)
* [ ] [Feature: #88807 - AdminPanel RequestEnricherInterface has been introduced](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Feature-88807-AdminPanelRequestEnricherInterfaceHasBeenIntroduced.html)

Deprecation
* [ ] [Deprecation: #80420 - EmailFinisher single address options](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Deprecation-80420-EmailFinisherSingleAddressOptions.html)
* [ ] [Deprecation: #82669 - Streamline Backend route path inconsistencies](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Deprecation-82669-StreamlineBackendRoutePathInconsistencies.html)
* [ ] [Deprecation: #85895 - Deprecate File::_getMetaData()](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Deprecation-85895-DeprecateFile_getMetaData.html)
* [ ] [Deprecation: #87200 - EmailFinisher FORMAT_* constants](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Deprecation-87200-EmailFinisherFormatContants.html)
* [ ] [Deprecation: #87200 - EmailFinisher “format” option](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Deprecation-87200-EmailFinisherFormatOption.html)
* [ ] [Deprecation: #87305 - Use constructor injection in DataMapper](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Deprecation-87305-UseConstructorInjectionInDataMapper.html)
* [ ] [Deprecation: #87332 - Avoid runtime reflection calls in ObjectAccess](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Deprecation-87332-AvoidRuntimeReflectionCallsInObjectAccess.html)
* [ ] [Deprecation: #87550 - Use controller classes when registering plugins/modules](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Deprecation-87550-UseControllerClassesWhenRegisteringPluginsmodules.html)
* [ ] [Deprecation: #87613 - Deprecate TYPO3CMSExtbaseUtilityTypeHandlingUtility::hex2bin](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Deprecation-87613-DeprecateTYPO3CMSExtbaseUtilityTypeHandlingUtilityhex2bin.html)
* [ ] [Deprecation: #87882 - File related controllers moved to EXT:filelist](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Deprecation-87882-FileRelatedControllersMovedToEXTfilelist.html)
* [ ] [Deprecation: #87894 - GeneralUtility::idnaEncode](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Deprecation-87894-GeneralUtilityidnaEncode.html)
* [ ] [Deprecation: #88366 - Default caching framework cache names changed](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Deprecation-88366-DefaultCachingFrameworkCacheNamesChanged.html)
* [ ] [Deprecation: #88406 - setCacheHash/noCacheHash options in ViewHelpers and UriBuilder](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Deprecation-88406-SetCacheHashnoCacheHashOptionsInViewHelpersAndUriBuilder.html)
* [ ] [Deprecation: #88428 - top.rawurlencode and top.str_replace](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Deprecation-88428-ToprawurlencodeAndTopstr_replace.html)
* [ ] [Deprecation: #88432 - Replaced md5.js with an AMD module](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Deprecation-88432-ReplacedMd5jsWithAnAMDModule.html)
* [ ] [Deprecation: #88433 - Deprecate top.openUrlInWindow](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Deprecation-88433-DeprecateTopopenUrlInWindow.html)
* [ ] [Deprecation: #88473 - TypoScriptFrontendController->settingLocale](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Deprecation-88473-TypoScriptFrontendController-settingLocale.html)
* [ ] [Deprecation: #88499 - BackendUtility::getViewDomain](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Deprecation-88499-BackendUtilitygetViewDomain.html)
* [ ] [Deprecation: #88554 - Deprecated methods in VersionNumberUtility](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Deprecation-88554-DeprecatedMethodsInVersionNumberUtility.html)
* [ ] [Deprecation: #88559 - $TSFE->sys_language_isocode](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Deprecation-88559-TSFE-sys_language_isocode.html)
* [ ] [Deprecation: #88567 - $GLOBALS[‘LOCAL_LANG’]](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Deprecation-88567-GLOBALS_LOCAL_LANG.html)
* [ ] [Deprecation: #88569 - Locales::initialize() in favor of regular singleton instance](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Deprecation-88569-LocalesinitializeInFavorOfRegularSingletonInstance.html)
* [ ] [Deprecation: #88651 - Replace TYPO3/CMS/Backend/SplitButtons with TYPO3/CMS/Backend/DocumentSaveActions](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Deprecation-88651-ReplaceTYPO3CMSBackendSplitButtonsWithTYPO3CMSBackendDocumentSaveActions.html)
* [ ] [Deprecation: #88662 - Deprecated backend route xMOD_tximpexp](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Deprecation-88662-DeprecatedBackendRouteXMOD_tximpexp.html)
* [ ] [Deprecation: #88746 - PageRepository PHP class moved from Frontend to Core Extension](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Deprecation-88746-PageRepositoryPHPClassMovedFromFrontendToCoreExtension.html)
* [ ] [Deprecation: #88792 - forceTemplateParsing in TSFE and TemplateService](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Deprecation-88792-ForceTemplateParsingInTSFEAndTemplateService.html)
* [ ] [Deprecation: #88807 - AdminPanel InitializableInterface has been deprecated](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Deprecation-88807-AdminPanelInitializableInterfaceHasBeenDeprecated.html)

Important
* [ ] [Important: #87427 - ClassSchema constants marked as private](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Important-87427-ClassSchemaConstantsMarkedAsPrivate.html)
* [ ] [Important: #87516 - Remove core HTTP RequestHandlerInterface](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Important-87516-RemoveCoreHTTPRequestHandlerInterface.html)
* [ ] [Important: #87594 - Classes use strict mode and scalar type hints](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Important-87603-ClassesUseStrictModeAndScarlarTypeHints.html)
* [ ] [Important: #87894 - Removed PHP dependency algo26-matthias/idna-convert](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Important-87894-RemovedPHPDependencyAlgo26-matthiasidna-convert.html)
* [ ] [Important: #87980 - “Page is being generated” message has been removed](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Important-87980-PageIsBeingGeneratedMessageHasBeenRemoved.html)
* [ ] [Important: #88043 - TypeScript sources moved into Build directory](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Important-88043-TypeScriptSourcesMovedIntoBuildDirectory.html)
