### ISSUE TITLE
Documentation updates related to Changelog 10.2

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/T3DocTeam#118]
php generate-changelog-issue.php "https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Index.html"
Breaking

Features
* [ ] [Feature: #79445 - Add Multistep Wizard](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-79445-AddMultistepWizard.html)
* [ ] [Feature: #79445 - Improve form creation wizard](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-79445-ImproveFormCreationWizard.html)
* [ ] [Feature: #82706 - Render fieldset labels in form templates](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-82706-RenderFieldsetLabelsInFormTemplates.html)
* [ ] [Feature: #84203 - Unify form setup YAML loading](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-84203-UnifyFormSetupYAMLLoading.html)
* [ ] [Feature: #84713 - Access single values in form templates](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-84713-AccessSingleFormValuesInTemplates.html)
* [ ] [Feature: #84990 - Add event for checking external links in RTE](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-84990-AddEventForCheckingExternalLinksInRTE.html)
* [ ] [Feature: #84990 - Mark broken file links in RTE](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-84990-MarkBrokenFileLinksInRTE.html)
* [ ] [Feature: #85592 - Add site title configuration to sites module](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-85592-AddSiteTitleConfigurationToSitesModule.html)
* [ ] [Feature: #86759 - Support nomodule attribute for JavaScript includes](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-86759-SupportNomoduleAttributeForJavaScriptIncludes.html)
* [ ] [Feature: #86918 - Add additional configuration for external link types in Linkvalidator](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-86918-AddAdditionalConfigurationForExternalLinkTypesInLinkvalidator.html)
* [ ] [Feature: #86967 - Allow fetching uid of a LazyLoadingProxy without loading the object first](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-86967-AllowFetchingUidOfALazyLoadingProxyWithoutLoadingTheObjectFirst.html)
* [ ] [Feature: #87380 - Introduce SiteLanguageAwareInterface to denote site language awareness](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-87380-IntroduceSiteLanguageAwareInterfaceToDenoteSiteLanguageAwareness.html)
* [ ] [Feature: #87798 - Provide a way to sort form lists in ext:form](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-87798-ProvideAWayToSortFormListsInExtform.html)
* [ ] [Feature: #88102 - Frontend Login Form Via Fluid And Extbase](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-88102-FrontendLoginViaFluidAndExtbase.html)
* [ ] [Feature: #88110 - Felogin extbase password recovery](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-88110-FeloginExtbasePasswordRecovery.html)
* [ ] [Feature: #88238 - FeatureToggle: form.legacyUploadMimeTypes](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-88238-FeatureToggleFormlegacyUploadMimeTypes.html)
* [ ] [Feature: #88902 - Feature Switch: Redirect and Base Redirect Middlewares can be reordered](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-88902-FeatureSwitchRedirectAndStaticRoutesMiddlewaresCanBeReordered.html)
* [ ] [Feature: #88950 - Add “storeSession” argument to Widget ViewHelpers](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-88950-AddStoreSessionArgumentToWidgetViewHelpers.html)
* [ ] [Feature: #89171 - Added possibility to have multiple sitemaps](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-89171-AddedPossibilityToHaveMultipleSitemaps.html)
* [ ] [Feature: #89398 - Support for environment variables in imports in site configurations](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-89398-SupportForEnvironmentVariablesInImportsInSiteConfigurations.html)
* [ ] [Feature: #89458 - Show link to online docs in extension manager](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-89458-ShowLinkToOnlineDocsInExtensionManager.html)
* [ ] [Feature: #89526 - FeatureFlag: betaTranslationServer](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-89526-FeatureFlagBetaTranslationServer.html)
* [ ] [Feature: #89577 - New PSR-14 based events for File Abstraction Layer](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-89577-NewPSR-14BasedEventsForFileAbstractionLayer.html)
* [ ] [Feature: #89603 - Introduce native pagination for lists](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-89603-IntroduceNativePaginationForLists.html)
* [ ] [Feature: #89718 - Unified PHP API for loading PageTSconfig](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-89718-UnifiedPHPAPIForLoadingPageTSconfig.html)
* [ ] [Feature: #89733 - New PSR-14 events for existing Signal Slots in Core Extension](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-89733-NewPSR-14EventsForExistingSignalSlotsInCoreExtension.html)
* [ ] [Feature: #89746 - Custom icon for record browser button in forms](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-89746-CustomIconForRecordBrowserButtonInForms.html)
* [ ] [Feature: #89747 - Custom tables with record browser in forms](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-89747-CustomTablesWithRecordBrowserInForms.html)

Deprecation
* [ ] [Deprecation: #85592 - Deprecated site title configuration](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-85592-DeprecatedSiteTitleConfiguration.html)
* [ ] [Deprecation: #88238 - Allowed MIME types of FileUpload and ImageUpload](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-88238-AllowedMimeTypesOfFileUploadAndImageUpload.html)
* [ ] [Deprecation: #89331 - FormEngine legacy functions](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-89331-FormEngineLegacyFunctions.html)
* [ ] [Deprecation: #89468 - Deprecate injection of EnvironmentService in Web Request](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-89468-DeprecateInjectionOfEnvironmentServiceInWebRequest.html)
* [ ] [Deprecation: #89554 - Deprecate TYPO3CMSExtbaseMvcControllerAbstractController](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-89554-DeprecateTYPO3CMSExtbaseMvcControllerAbstractController.html)
* [ ] [Deprecation: #89577 - FAL SignalSlot handling migrated to PSR-14 events](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-89577-FALSignalSlotHandlingMigratedToPSR-14Events.html)
* [ ] [Deprecation: #89579 - ServiceChains require an array for excluded Service keys](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-89579-ServiceChainsRequireAnArrayForExcludedServiceKeys.html)
* [ ] [Deprecation: #89631 - Use Environment API to fetch application context](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-89631-UseEnvironmentAPIToFetchApplicationContext.html)
* [ ] [Deprecation: #89718 - Legacy PageTSconfig parsing lowlevel API](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-89718-LegacyPageTSconfigParsingLowlevelAPI.html)
* [ ] [Deprecation: #89722 - GMENU_LAYERS related property TSFE->divSection](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-89722-GMENU_LAYERSRelatedPropertyTSFE-divSection.html)
* [ ] [Deprecation: #89733 - Signal Slots in Core Extension migrated to PSR-14 events](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-89733-SignalSlotsInCoreExtensionMigratedToPSR-14Events.html)
* [ ] [Deprecation: #89742 - Form mixins](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-89742-FormMixins.html)
* [ ] [Deprecation: #89756 - BackendUtility::TYPO3_copyRightNotice](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-89756-BackendUtilityTYPO3_copyRightNotice.html)

Important
* [ ] [Important: #84221 - Restructuring of form setup](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Important-84221-RestructuringOfFormSetup.html)
* [ ] [Important: #87518 - Use prepared statements for pdo_mysql per default](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Important-87518-UsePreparedStatementsForPdo_mysqlPerDefault.html)
* [ ] [Important: #88655 - Changed loading order of RTE Configuration](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Important-88655-ChangedLoadingOrderOfRTEConfiguration.html)
* [ ] [Important: #89645 - Removed systemLog options](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Important-89645-RemovedSystemLogOptions.html)
* [ ] [Important: #89764 - Incompatible environment related dependency injection services have been removed](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Important-89764-IncompatibleEnvironmentRelatedDependencyInjectionServicesHaveBeenRemoved.html)
