### ISSUE TITLE
Documentation updates related to Changelog 9.5.x

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/T3DocTeam#119]
Workflow for updating docs based on Changelog is documented on https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/GeneralConventions/HowToUpdateDocs.html

----

Issue created by[ t3doc-tools](https://github.com/TYPO3-Documentation/t3docs-tools):

    php generate-changelog-issue.php "https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.5.x/Index.html"

----

**Breaking**

**Features**
* [ ] [Feature: #83334 - Add improved building of query strings](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.5.x/Feature-83334-AddImprovedBuildQueryString.html)
* [ ] [Feature: #86740 - Replace characters in slug](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.5.x/Feature-86740-AllowRemovalOfSlashInSlug.html)
* [ ] [Feature: #86762 - Enhanced fallback modes for translated content](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.5.x/Feature-86762-EnhancedFallbackModesForTranslatedContent.html)
* [ ] [Feature: #86826 - Recursive record sitemap](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.5.x/Feature-86826-RecursiveRecordSitemap.html)
* [ ] [Feature: #86881 - Support of Features in expression language](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.5.x/Feature-86881-SupportOfFeaturesInExpressionLanguage.html)
* [ ] [Feature: #86973 - TypoScript getText property siteLanguage](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.5.x/Feature-86973-TypoScriptGetTextPropertySiteLanguage.html)
* [ ] [Feature: #87033 - New TypoScript Property config.htmlTag.attributes](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.5.x/Feature-87033-NewTypoScriptPropertyConfightmlTagattributes.html)
* [ ] [Feature: #87085 - Fallback options for slug fields](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.5.x/Feature-87085-FallbackOptionsForSlugFields.html)
* [ ] [Feature: #87610 - New FAL API to search for files including their meta data](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.5.x/Feature-87610-New-FAL-API-to-search-for-files.html)
* [ ] [Feature: #87748 - Add SiteProcessor](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.5.x/Feature-87748-AddSiteProcessor.html)
* [ ] [Feature: #88198 - TCA-based Slug modifiers for extensions](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.5.x/Feature-88198-TCA-basedSlugModifiersForExtensions.html)

**Deprecation**
* [ ] [Deprecation: #86907 - Deprecate usage of dependency injection with non public properties](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.5.x/Deprecation-86907-DeprecateUsageOfDependencyInjectionWithNonPublicProperties.html)
* [ ] [Deprecation: #87277 - Fluid Class Aliases](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.5.x/Deprecation-87277-FluidClassAliases.html)

**Important**
* [ ] [Important: #65636 - File meta data can now be edited on read only storages](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.5.x/Important-65636-AllowMetaDataEditingOnReadOnlyStorages.html)
* [ ] [Important: #76166 - X-UA-Compatible not set in backend anymore](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.5.x/Important-76166-X-UA-CompatibleNotSetInBackendAnymore.html)
* [ ] [Important: #84985 - Unified Workspace Restriction for Database Queries](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.5.x/Important-84985-UnifiedWorkspaceRestrictionForDatabaseQueries.html)
* [ ] [Important: #86577 - Query parameters are now included in canonicalized URLs](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.5.x/Important-86577-QueryParametersAreNowIncludedInCanonicalizedUrls.html)
* [ ] [Important: #86785 - Calling scheduler command on CLI throws error if not in /var/www/html](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.5.x/Important-86785-CallingSchedulerTaskThrowsLoggerError.html)
* [ ] [Important: #86994 - Indexed Search indexes pages using route enhancers](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.5.x/Important-86994-IndexedSearchWithRouteEnhancers.html)
* [ ] [Important: #87028 - Access objects from ObjectStorage using numeric value](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.5.x/Important-87028-AccessObjectsFromObjectStorageUsingNumericValue.html)
* [ ] [Important: #87518 - Use prepared statements for pdo_mysql per default](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.5.x/Important-87518-UsePreparedStatementsForPdo_mysqlPerDefault.html)
* [ ] [Important: #88045 - Locales dependencies configuration](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.5.x/Important-88045-LocalesDependenciesConfiguration.html)
