### ISSUE TITLE
Structure of Overview pages on docs home (Guides & Tutorials, References, etc.)

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/T3DocTeam#13]
# Problem
* If you are not already familiar with TYPO3, you often don't know where to go first or find what you are looking for
* Some terms are not self-explanatory and not being used consistently (e.g. some people did not right away know what "site package tutorial" is. 
* 2 different guides for Extbase / Fluid confusing
* there is abundance of information in various places (blogs, snippets, YouTube videos, Tell me something about, guides / tutorials, wiki, fluid on docs.typo3.org, fluid on github, system extensions, etc. ...) but not enough help for 
  * where to find what
  * where to get started
  * finding specific developer information

# Possible solutions

* [ ] The lists on the homepage ("References" and "Guides and Tutorials") can be restructured and revised, especially to guide new people. 
* [x] Descriptions can be added for all manuals (this is WIP with latest Pull Requests)
* [ ] Information can be structured by target group (e.g. editors, integrators, developers, sysads)
  * [ ] PR "Resources for Developers" can be debated: https://github.com/TYPO3-Documentation/DocsTypo3Org-Homepage/pull/17

See also, other examples for target groups, e.g. https://www.neos.io/

![neos](https://user-images.githubusercontent.com/13206455/43203681-297c7f96-901f-11e8-8df6-b428f9a0b9fb.png)

* [ ]  A separate "Getting started" page can be added, where resources are linked (not just docs, but also blogs and videos, if necessary)
* [ ] General restructuring 
* [ ] Add a "tour of the TYPO3 documentation" for new people to get them started 

# Tasks

* [ ] ...

**Comment by DanielSiepmann** [comment]
Looks like multiple sub-topics to me which should, maybe, be tackled in different ways.
This one should be on our list for a first personal meetup!

Might be to difficult to discuss this on a digital way. But we should add our points of views and ideas here to have ab base for our meeting.

**Comment by sypets** [comment]
Some things have been improved on the homepage, so I would like to close this issue for now. Feel free to reopen or open new issues for specific topics.

What was improved:
* lists in "tutorials & guides" and "Core documentation" now all have descriptions
* some WIP was removed
* "References" was renamed "Core documentation"

The qualms I still have with 2 manuals for Extbase / Fluid and Site package / Template tutorials cannot be resolved with a better structure on the homepage. I am confident that with the merging of manuals and possibly a separate fluid manual that these problems will be taken care of in the future.
