### ISSUE TITLE
Define general structure of documentation

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/T3DocTeam#17]
# Goal

Clearly comprehensible structure of all manuals. The reader knows what to find where and can either lookup specific material or find the best resource for his learning level and goal. The material is up-to-date. Nothing major is missing

-----

Note: Some of these points may later be moved to separate issues. But, this matter must be considered in its entirety. 

# General Tasks

* [ ] Revise general structure. What should be where (in which manual). What should be merged, be deprecated? Is anything missing?

# Specific Tasks

* [ ]  Where should **sysext** Extensions be documented? In a Documentation folder in the extension or in a docs repo? (currently done differently, e.g. seo in "TYPO3 Explained", 
* [ ] **Core API**: Define Core API What should go there. How should it be structured?
* [ ] "Restructure Development documentation (Extbase / Fluid, core API, ...)" #10
* [ ] Extbase is missing in the Core API, if the initial definition is followed through, the Core API should contain an Extbase reference. Pros / Cons ...?
* [x] [Snippet](https://docs.typo3.org/typo3cms/Snippets/) section: Some of it outdated.  #74
* [x]  Wiki: see #8 and where should things that are moved from the Wiki go?

# Already achieved

* [x] The Core API has been merged with some of the other manuals (Inside TYPO3, cga, fal, security, TypoScript syntax)
* [x] There are [various place](https://docs.typo3.org/typo3cms/Teams/T3DocTeam/Drafts/00ListOfManualsAboutDocumentation.html) where "Writing documentation" is documented. Should this be merged into 1 manual?
* [x]  Should documentation contribution and translation contribution be added to [Contribution Guide](https://docs.typo3.org/typo3cms/ContributionWorkflowGuide/)? Doc contribution is now in "Writing Documentation"

this was already good:
* Some of the manuals are in a good state with a logical structure, no further intervention necessary

**Comment by DanielSiepmann** [comment]
>  Where should sysext Extensions be documented? In a Documentation folder in the extension or in a docs repo?

I would say with the code, so as it's now. This way the Core Team can review changes together with documentation and changelog.

>  The ViewHelper reference is a developer reference (in it's current state and later in the generated form). Should it be moved to Core API or where should it go?

This is already discussed here: #9 

>  There are various place where "Writing documentation" is documented. Should this be merged into 1 manual?

I would find this useful. Then only one source exists and no one can get confused where to look at. Also we have only one repository with issues and one base to maintain.

>  Should documention contribution and translation contribution be added to Contribution Guide?

I would like to have a single place about "How to contribute" with sub sections based on the topics. But also to contain a section based on "skills" so targeting specific users like editors, marketers, translators, etc. This can be a single section linking to the existing sections. Just guiding the user to his area.

**Comment by sypets** [comment]
@DanielSiepmann  About your answers

1. sysext exensions: Agreed. That's how it's currently done.
2. Agreed. Generating VH reference is discussed in #9. The general structure of the developer docs and where this generated ref should go is another topic, I think
3. I am very much for merging the docs about docs. We should think about the structure, though. I will very shortly create something in our drafts section or push a PR. 
4. I am having second thoughts about 1 manual for contribution, see #22 

Unfortunately, some of these topics are too big for one issue. I think I will create seperate issues for them: 

* documentation guide(s) : todo
* contribution guide(s) : #22

Problem I have right now: I don't see a good way to structure issues on Github. On forge, you can create stories and epics. You can assign issues as subtasks. For this problem, I also created an issue: #21

**Comment by sypets** [comment]
Several tasks are already solved. The rest needs decisions. This issue is too general to proceed right now.

**Comment by alexander-nitsche** [comment]
> Where should sysext Extensions be documented? In a Documentation folder in the extension or in a docs repo? (currently done differently, e.g. seo in "TYPO3 Explained",

In the Documentation/ folder of each extension, as is done for third-party extensions. Most system extensions have it applied, some might be missing.

> Extbase is missing in the Core API, if the initial definition is followed through, the Core API should contain an Extbase reference. Pros / Cons ...?

If the initial definition is followed through, the system extension folders should contain the basic documentation of each, and the Core API or other sources should hold tutorials and how-tos. For example a chapter about general extension development, mentioning there, when to use Extbase.

**Comment by DavidBruchmann** [comment]
Due to changes in the last months I think the ideas of @alexander-nitsche  are somehow covered and this issue can be closed @linawolf (I've no access for it).
