### ISSUE TITLE
Make information about rendering with Docker easier to find and merge into one place

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/T3DocTeam#58]
Rendering information is currently in 3 places:
* [Writing Documentation](https://docs.typo3.org/typo3cms/HowToDocument/RenderingDocs/Quickstart.html)
* [Readme in repo of Docker image](https://github.com/t3docs/docker-render-documentation/blob/master/README.rst)
* [Render TYPO3 Documentation Guide](https://docs.typo3.org/typo3cms/RenderTYPO3DocumentationGuide/Index.html#start)

# Which resource should we use in the future?

We usually pointed people to the README.rst in the past. That is where the up-to-date information is, currently. I think, for now, we should change all links to point to that README.rst. If at some later point we decide to move that information to the rendering guide, we can do that. But right now, it is confusing, because you sometimes have to click 2 or more links and there is information in several places, part of it is outdated or incomplete. 

**Advantages** of using README.rst as main resource for rendering with Docker:
* This is where the docker image is maintained, so it's a good idea to maintain the documentation there as well. That way documentation, it is easier to keep documentation up-to-date with functionality.

**Disadvantages** of using README.rst as main resource for rendering with docker
* All in one file, toc (table of contents) not automatically created, this has now been fixed by using `.. contents:: ` directive to create toc
* Can't render the README.rst locally with current workflow, see also https://github.com/t3docs/docker-render-documentation/issues/31
* People are directed from official documentation to a Readme on GitHub with different layout, breaks the flow of reading, leads to confusing (e.g. "is this still official documentation"?)

# Todos 

* [ ] Decide which documentation should be documentation about "How to render with Docker": [Readme on GitHub](https://github.com/t3docs/docker-render-documentation/blob/master/README.rst), "Rendering section in ["How to Document"](https://docs.typo3.org/typo3cms/HowToDocument/RenderingDocs/Index.html), or ["Rendering Guide"](https://docs.typo3.org/typo3cms/RenderTYPO3DocumentationGuide/Index.html#start)
* [ ]  Merge existing information into one place and link to that from the other sections
* [ ] define scope of [rendering guide](https://docs.typo3.org/typo3cms/RenderTYPO3DocumentationGuide/Index.html#start), remove outdated information, update information, remove WIP, to be written

**Comment by sypets** [comment]
Currently, googling for `typo3 render documentation` gets this as first result for me:

https://docs.typo3.org/typo3cms/RenderTYPO3DocumentationGuide/

not very helpful: 

![render-startpage](https://user-images.githubusercontent.com/13206455/52163430-25ca7380-26e2-11e9-80a3-6a36b6578b1c.png)

**Comment by sypets** [comment]
done.
