### ISSUE TITLE
Define workflow for moving content from Wiki to docs

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/T3DocTeam#99]
There is a more general issue [What to do with the Wiki](https://github.com/TYPO3-Documentation/T3DocTeam/issues/8). **This** issue (#99) is a subtask that focuses on the workflow!

# Todo: 

Define and communicate workflow for the following steps

* move / merge / remove content ...
* add redirects (current idea: make configuration available for PR)
* delete pages
* how to use the categories (which categories to use for working on the wiki?)

Todos:

* [x] add information about the procedure about migrating & cleaning up to the pages that are already about contributing to the wiki (possibly reduce number of pages):
  * https://wiki.typo3.org/Main_Page
  * https://wiki.typo3.org/Help:Contents#Teamwork_-_draft_review_publish_delete_merge_outdated
  * https://wiki.typo3.org/WikiMigration
  * https://wiki.typo3.org/OverviewOfWiki
  * have one short section with easy to follow steps
*  possibly reduce categories (find duplicate and similar categories)
   * [Delete](https://wiki.typo3.org/Category:Delete) category shows all pages with `{{delete}}` tag 
   * [ ] [CandidateForRemoval](https://wiki.typo3.org/Category:CandiateForRemoval) is deprecated : use `{{delete}}` tag instead!
   * [ ] https://wiki.typo3.org/Category:NeedsRedirect can possibly be replaced by `{{delete}}` tag
   * https://wiki.typo3.org/Category:Outdated : content is outdated
   * [ExtensionsOnlyDocumentation](https://wiki.typo3.org/Category:ExtensionsOnlyDocumentation) : extension documentation

# Open decisions

* see section in #8

# Resources

* RSS feed for wiki changes: https://wiki.typo3.org/wiki/api.php?hidebots=1&urlversion=1&days=7&limit=50&action=feedrecentchanges&feedformat=atom
  * Tip: use https://feedly.com
  * OR see "Wiki contribution" > "Review recent changes" in menu: https://wiki.typo3.org/Special:RecentChanges

# Related

* #8 (issue)
* [Wiki migratation, decisions](https://github.com/orgs/TYPO3-Documentation/projects/3#card-25087997) (project: issues can be assigned to a project, see also **Projects** on the right side!)

**Comment by sypets** [comment]
removed (pages already had redirects):

https://wiki.typo3.org/TYPO3.CMS/Releases/7.0/Deprecation
https://wiki.typo3.org/TYPO3.CMS/Releases/7.0/Feature
https://wiki.typo3.org/TYPO3.CMS/Releases/7.1/Breaking
https://wiki.typo3.org/TYPO3.CMS/Releases/7.1/Deprecation
https://wiki.typo3.org/TYPO3.CMS/Releases/7.1/Feature
https://wiki.typo3.org/TYPO3.CMS/Releases/7.2/Breaking
https://wiki.typo3.org/TYPO3.CMS/Releases/7.2/Deprecation
https://wiki.typo3.org/TYPO3.CMS/Releases/7.2/Feature
https://wiki.typo3.org/TYPO3.CMS/Releases/7.3/Breaking
https://wiki.typo3.org/TYPO3.CMS/Releases/7.3/Deprecation
https://wiki.typo3.org/TYPO3.CMS/Releases/7.3/Feature
https://wiki.typo3.org/TYPO3.CMS/Releases/7.3/Important
https://wiki.typo3.org/TYPO3.CMS/Releases/7.4/Breaking
https://wiki.typo3.org/TYPO3.CMS/Releases/7.4/Deprecation
https://wiki.typo3.org/TYPO3.CMS/Releases/7.4/Feature
https://wiki.typo3.org/TYPO3.CMS/Releases/7.4/Important
https://wiki.typo3.org/TYPO3.CMS/Releases/7.5/Breaking
https://wiki.typo3.org/TYPO3.CMS/Releases/7.5/Deprecation
https://wiki.typo3.org/TYPO3.CMS/Releases/7.5/Feature
https://wiki.typo3.org/TYPO3.CMS/Releases/7.5/Important
https://wiki.typo3.org/TYPO3.CMS/Releases/7.6/Breaking
https://wiki.typo3.org/TYPO3.CMS/Releases/7.6/Deprecation
https://wiki.typo3.org/TYPO3.CMS/Releases/7.6/Feature
https://wiki.typo3.org/TYPO3.CMS/Releases/7.6/Important

**Comment by linawolf** [comment]
Dealing with outdated extension manuals
Hello Everyone I am still thinking about how to deal with outdated extension manuals, expecially since I started sorting through the Extension category in the wiki. I still think even if the Documentation is very outdated it would not be good to throw it away. I would prefere to mark it as outdated and keep it in a format that can still be read in 10 years. Maybe pdf or pure html. People might still need the information to update old projects or to have a look what the old extension could do at the time being. I think something like an archive would be good
I started collecting such extension manuals in this category: https://wiki.typo3.org/Category:ExtensionsOnlyDocumentation and marked those where the information can be found in the TER or official documentation or that are merely a short listing of features to be deleted https://wiki.typo3.org/Category:Delete

**Comment by sypets** [comment]
The following information was added to the start page:

> For contributing to the Wiki, please see the following resources:
> * You're welcome to add tags to pages: [tags](https://wiki.typo3.org/Help:Contents#Teamwork_and_page_states_-_draft.2C_review.2C_publish.2C_delete.2C_merge.2C_outdated)
> * Read how we [manage the workflow in the wiki](https://wiki.typo3.org/Help:Contents).
> * For migrating Wiki content do the reST documentation on docs.typo3.org: [Wiki migration](https://wiki.typo3.org/WikiMigration)

**Comment by susannemoog** [comment]
Done with the wiki migration project I thin, I'll close this here.
